function fncSearchKeyDown(a,b,d){try{if(a==13)d!=undefined?document.getElementById("id_search_button_sub").click():document.getElementById("id_search_button").click();if(b==fncGetResourceByResourceId("enter_search_keyword"))if(document.getElementById("id_search")){document.getElementById("id_search").value="";document.getElementById("id_search").style.color="#000000"}else if(document.getElementById("id_search_texts")){document.getElementById("id_search_texts").value="";document.getElementById("id_search_texts").style.color=
"#000000"}}catch(c){}}function fncGetResourceByResourceId(a){try{for(var b=eval(resource),d=b.length,c=0;c<d;c++)if(b[c].id==a)return b[c].value;return""}catch(i){}}function fncLoadResource(){try{for(var a=eval(resource),b=a.length,d=0;d<b;d++){if(document.getElementById("id_res_"+a[d].id))document.getElementById("id_res_"+a[d].id).innerHTML=a[d].value;if(document.title=="")if(a[d].id=="title")document.title=a[d].value}}catch(c){}}
function fncSearchBox(){try{if(document.getElementById("id_search")){if(document.getElementById("id_search").value=="")document.getElementById("id_search").value=fncGetResourceByResourceId("enter_search_keyword");if(document.getElementById("id_search").value==fncGetResourceByResourceId("enter_search_keyword"))document.getElementById("id_search").style.color="#808080";document.getElementById("id_search").onclick=function(){if(this.value==fncGetResourceByResourceId("enter_search_keyword")){this.value=
"";document.getElementById("id_search").style.color="#000000"}};document.getElementById("id_search").onblur=function(){if(this.value==""){this.value=fncGetResourceByResourceId("enter_search_keyword");document.getElementById("id_search").style.color="#808080"}}}}catch(a){}try{if(document.getElementById("id_search_sub")){if(document.getElementById("id_search_sub").value=="")document.getElementById("id_search_sub").value=fncGetResourceByResourceId("enter_search_keyword");if(document.getElementById("id_search_sub").value==
fncGetResourceByResourceId("enter_search_keyword"))document.getElementById("id_search_sub").style.color="#808080";document.getElementById("id_search_sub").onclick=function(){if(this.value==fncGetResourceByResourceId("enter_search_keyword")){this.value="";document.getElementById("id_search_sub").style.color="#000000"}};document.getElementById("id_search_sub").onblur=function(){if(this.value==""){this.value=fncGetResourceByResourceId("enter_search_keyword");document.getElementById("id_search_sub").style.color=
"#808080"}}}}catch(b){}}var search;
function fncDoSearch(a){try{var b=document.getElementById("id_search").value;var d=b=b.trim();if(b==""||b==fncGetResourceByResourceId("enter_search_keyword"))document.getElementById("id_search_results").innerHTML=fncGetNoneFoundMessage("");else{var c=/([$()\-^\\\|\[\]{},:+*.?])/g;if(c.exec(b)!=null)b=b.replace(c,"\\$1");c=/(&)/g;if(c.exec(b)!=null){b=b.replace(c,"&amp;");d=d.replace(c,"&amp;")}c=/(<)/g;if(c.exec(b)!=null){b=b.replace(c,"&lt;");d=d.replace(c,"&lt;")}c=/(>)/g;if(c.exec(b)!=null){b=
b.replace(c,"&gt;");d=d.replace(c,"&gt;")}var i=false,g=[],h=b.length;for(c=0;c<h;c++){var f=b.substring(c,c+1);if(f=='"'||f=="\u201d"||f=="\u201c"){f="";i=!i}else if(i&&(f==" "||f=="\u3000"||f=="\t"))f="___SPACE___";g.push(f)}b=g.join("");i=false;g=[];h=d.length;for(c=0;c<h;c++){f=d.substring(c,c+1);if(f=='"'||f=="\u201d"||f=="\u201c"){f="";i=!i}else if(i&&(f==" "||f=="\u3000"||f=="\t"))f="___SPACE___";g.push(f)}d=g.join("");f=/[\s\u3000]+/;var j=b.split(f),m=d.split(f);if(j.join("")==""){document.getElementById("id_search").value=
fncGetResourceByResourceId("enter_search_keyword");document.getElementById("id_search").style.color="#808080";document.getElementById("id_search_results").innerHTML=fncGetNoneFoundMessage("");return false}h=j.length;for(c=0;c<h;c++)j[c]=j[c].replace(/___SPACE___/g," ");h=m.length;for(c=0;c<h;c++)m[c]=m[c].replace(/___SPACE___/g," ");d=m.join(" ");var k=fncGetConstantByName("search_show_around");k||(k=50);i=f=k;var o=fncGetConstantByName("search_show_result_count");o||(o=10);var q=fncGetConstantByName("search_page_max_range");
q||(q=5);var s=parseInt(q/2),C=parseInt(q/2);k=0;g=[];var l=[];if(strWindowType!="GLOSSARY"){g.push("");g.push('<div class="search_result_conditions" id="id_search_result_item"></div>')}for(var y=j.length,p=0;p<y;p++){var n=j[p];if(document.getElementById("id_search_options_multibyte"))if(document.getElementById("id_search_options_multibyte").checked){n=fncConvertSearchText(n,true);j[p]=n}var z="i";if(document.getElementById("id_search_options_case")){if(document.getElementById("id_search_options_case").checked)z=
""}else if(fncGetCookie("SEARCH-OPTIONS-CASE")=="TRUE")z=""}h=search.length;for(c=0;c<h;c++){var v=search[c].body,Q=search[c].toc_id,D=fncGetEncodeText(search[c].title);D=D.replace(/\u00b6+/g,"");if(v){y=j.length;var H=[];for(p=0;p<y;p++){n=j[p];var E="("+n+")",I=RegExp(E,z);if(I.exec(v)==null)break;else{var x=v.search(I);if(x!=-1){var t="",J=v.substring(0,x),K=J.lastIndexOf("&");if(n!="&")if(K!=-1)t=J.substring(K);var w="",L=v.substring(x+m[p].length),M=L.indexOf(";");if(m[p]!=";")if(M!=-1)w=L.substring(0,
M+1);var A=t+m[p].toLowerCase()+w;if(A=="&amp;"||A=="&lt;"||A=="&gt;"||A=="&quot;")break;for(var B=v.substring(x-f,x+i);;)if(B.substring(0,1).match(/[\u0E31]|[\u0E47-\u0E4E]|[\u0E34-\u0E3A]/)!=null)B=B.substring(1);else break;H.push(B)}}if(p==j.length-1){k++;if(a*o>=k+0&&a*o-o<k+0){var e=fncGetEncodeText(H.join("..."));for(w=t=0;w<y;w++){switch(t){case 0:strMarkerColor=String.fromCharCode(8320);break;case 1:strMarkerColor=String.fromCharCode(8321);break;case 2:strMarkerColor=String.fromCharCode(8322);
break;case 3:strMarkerColor=String.fromCharCode(8323);break;case 4:strMarkerColor=String.fromCharCode(8324);break;case 5:strMarkerColor=String.fromCharCode(8325);break;case 6:strMarkerColor=String.fromCharCode(8326);break;case 7:strMarkerColor=String.fromCharCode(8327);break;case 8:strMarkerColor=String.fromCharCode(8328);break;case 9:strMarkerColor=String.fromCharCode(8329)}n=j[w];n=n.replace(/&amp;/g,String.fromCharCode(726));n=n.replace(/&quot;/g,String.fromCharCode(698));n=n.replace(/&lt;/g,String.fromCharCode(753));
n=n.replace(/&gt;/g,String.fromCharCode(754));E="("+n+")";var R=RegExp(E,"g"+z);e=e.replace(/&amp;/g,String.fromCharCode(726));e=e.replace(/&quot;/g,String.fromCharCode(698));e=e.replace(/&lt;/g,String.fromCharCode(753));e=e.replace(/&gt;/g,String.fromCharCode(754));e=e.replace(R,function(S){return String.fromCharCode(8261)+strMarkerColor+S+String.fromCharCode(8262)});e=e.replace(/\u02D6/g,"&amp;");e=e.replace(/\u02BA/g,"&quot;");e=e.replace(/\u02F1/g,"&lt;");e=e.replace(/\u02F2/g,"&gt;");t++;if(t>=
10)t=0}var T=RegExp("\u2046","g");e=e.replace(RegExp("\u2045([\u2080-\u2089])","g"),"<b>");e=e.replace(T,"</b>");e=e.replace(/\u2080/g,"0");e=e.replace(/\u2081/g,"1");e=e.replace(/\u2082/g,"2");e=e.replace(/\u2083/g,"3");e=e.replace(/\u2084/g,"4");e=e.replace(/\u2085/g,"5");e=e.replace(/\u2086/g,"6");e=e.replace(/\u2087/g,"7");e=e.replace(/\u2088/g,"8");e=e.replace(/\u2089/g,"9");e=e.replace(/\u00b6+/g,"");l.join("")==""&&l.push('<ul class="list impact">');l.push("<li>");l.push("<a href=\"javascript:fncOpenTopic('"+
Q+"', "+a+');void(0);">');l.push("<span>");l.push(D);l.push("</span>");l.push("<p>");l.push("...");l.push(e);l.push("...");l.push("</p>");l.push("</a>");l.push("</li>")}}}}}l.join("")!=""&&l.push("</ul>");g.push('<input id="id_search_texts" style="display:None;" value="'+b+'" />');document.getElementById("id_search_results").innerHTML=g.join("")+l.join("");document.getElementById("id_search_results").style.backgroundColor="#FFFFFF";window.scroll(0,0);b=[];b.push('<div class="turn-page">');b.push('<span class="inner">');
if(a>1){var r;r=document.documentElement.getAttribute("dir")=="rtl"?"../common/img/arrow_turnpage_right.png":"../common/img/arrow_turnpage_left.png";b.push('<a onclick="fncDoSearch('+(a-1)+');" class="left" href="#"><img src="'+r+'" alt="'+fncGetResourceByResourceId("search_prev")+'" /></a> ')}var u=parseInt(k/o);k%o!=0&&u++;o=1;r=u;if(a-s>1)o=a-s;if(document.getElementById("id_search_result_item")){s=[];if(k==0)s.push(fncGetNoneFoundMessage(d));else{var F;F=a*parseInt(fncGetConstantByName("search_show_result_count"))>
k?k:a*parseInt(fncGetConstantByName("search_show_result_count"));s.push("<h2>"+fncGetSearchFoundMessage(d)+"<span>"+fncGetSearchCountMessage(a,F,k)+"</span></h2>")}document.getElementById("id_search_result_item").innerHTML=s.join("")}if(q>=u){r=u;o=1}else if(a+C<=q)r=q;else if(a+C>=u){r=u;o=r-q+1}else r=a+C;for(c=o;c<=r;c++)a==c?b.push('<a onclick="fncDoSearch('+c+');" class="active" href="#">'+c+"</a>"):b.push('<a onclick="fncDoSearch('+c+');" href="#">'+c+"</a>");if(a+1<=u){var N;N=document.documentElement.getAttribute("dir")==
"rtl"?"../common/img/arrow_turnpage_left.png":"../common/img/arrow_turnpage_right.png";b.push(' <a onclick="fncDoSearch('+(a+1)+');" class="right" href="#"><img src="'+N+'" alt="'+fncGetResourceByResourceId("search_next")+'" /></a>')}k!=0&&b.push('<div class="item-number">'+fncGetSearchCountMessageBottom(a,F,k)+"</div>");b.push("</span>");b.push("</div>");document.getElementById("id_search_status").innerHTML=b.join("");if(strWindowType=="HOME"){var U=document.getElementById("id_search_texts").value;
fncSetCookie("SEARCH-KEYWORD",U)}var O=fncGetCookie("SEARCH-RESULT-SETTING");if(""!=O){var P=O.split(":"),G=P[1];if(P[0]==a)""!=G&&undefined!=G&&window.setTimeout("fncSearchResultScroll("+G+")",10);else fncSearchResultScroll(0)}else fncSearchResultScroll(0)}}catch(V){}}
function fncGetNoneFoundMessage(a){var b=[];b.push("<h2>"+fncGetSearchFoundMessage(a)+"</h2>");b.push('<div class="guidance">');b.push("<h3>"+fncGetResourceByResourceId("search_none_found_message_title")+"</h3>");b.push("<p><b>"+fncGetResourceByResourceId("search_none_found_message_body")+"</b></p>");b.push("<ul>");for(a=1;fncGetResourceByResourceId("search_none_found_message_"+a)!="";){b.push("<li>"+fncGetResourceByResourceId("search_none_found_message_"+a)+"</li>");a++}b.push("</ul>");b.push("</div>");
document.getElementById("id_inner").style.display="none";return b.join("")}function fncSearchResultScroll(a){document.getElementById("id_search_results").scrollTop=a}function fncOpenTopic(a,b){try{var d=encodeURIComponent(document.getElementById("id_search").value),c=a+".html?search="+d;fncSetSearchResultsInfo(b);window.open(c,"_self")}catch(i){window.open(c)}}
function fncSetSearchResultsInfo(a){try{document.getElementById("id_search_results")&&strWindowType!="GLOSSARY"&&fncSetCookie("SEARCH-RESULT-SETTING",a+":"+document.getElementById("id_search_results").scrollTop)}catch(b){}}function fncGetConstantByName(a){try{return eval(constant)[0][a]}catch(b){}}function fncGetCookiePrefixName(){try{return"EMANUAL-"+fncGetResourceByResourceId("pub_number")+"-"}catch(a){}}
function fncSetCookie(a,b){try{document.cookie=fncGetCookiePrefixName()+a+"="+encodeURIComponent(b)+";path=/;"}catch(d){}}function fncGetCookie(a){try{for(var b=document.cookie.split("; "),d=b.length,c=0;c<d;c++){var i=b[c].split("=");if(fncGetCookiePrefixName()+a==i[0])if(i[1])return decodeURIComponent(i[1])}return""}catch(g){}}
function fncConvertSearchText(a,b){try{var d="",c=fncGetRegExpArray();a=a.replace(/&lt;/g,"<");a=a.replace(/&gt;/g,">");a=a.replace(/&amp;/g,"&");for(var i=a.length,g=0;g<i;g++){var h=a.substring(g,g+1),f="";if(h.match(/[\u005C]/)){var j=a.substring(g+1,g+2);if(h.match(/([$()\-^\\\|\[\]{},:+*.?])/)){f=fncGetRegExpString(h+j,c);g++}}else if(h.match(/[\uFF66-\uFF9F]/)){j=a.substring(g+1,g+2);if(j.match(/[\uFF9E-\uFF9F]/)){var m=h+j;f=fncGetRegExpString(m,c);if(f!=m)g+=j.length}}else if(h.match(/[A-Za-z0-9]/)){var k=
h.charCodeAt(0)+65248,o=String.fromCharCode(k);f="("+h+"|"+o+")"}else if(h.match(/[\uFF21-\uFF3A\uFF41-\uFF5A\uFF10-\uFF19]/)){var q=h.charCodeAt(0)-65248;m=String.fromCharCode(q);f="("+m+"|"+h+")"}if(f=="")f=fncGetRegExpString(h,c);d+=f}if(b){d=d.replace(/&/g,"&amp;");d=d.replace(/</g,"&lt;");d=d.replace(/>/g,"&gt;")}return d}catch(s){}}
function fncGetRegExpString(a,b){for(var d=a,c=fncGetRegExpSeparator(),i=b.length,g=0;g<i;g++){for(var h=b[g],f=h.split(c),j=f.length,m=0;m<j;m++)if(f[m]==a){d=h.replace(c,"|");d="("+d+")";break}if(d!=a)break}return d}
function fncGetRegExpArray(){var a=fncGetRegExpSeparator();return["\uff71"+a+"\u30a2","\uff72"+a+"\u30a4","\uff73"+a+"\u30a6","\uff74"+a+"\u30a8","\uff75"+a+"\u30aa","\uff76"+a+"\u30ab","\uff77"+a+"\u30ad","\uff78"+a+"\u30af","\uff79"+a+"\u30b1","\uff7a"+a+"\u30b3","\uff7b"+a+"\u30b5","\uff7c"+a+"\u30b7","\uff7d"+a+"\u30b9","\uff7e"+a+"\u30bb","\uff7f"+a+"\u30bd","\uff80"+a+"\u30bf","\uff81"+a+"\u30c1","\uff82"+a+"\u30c4","\uff83"+a+"\u30c6","\uff84"+a+"\u30c8","\uff85"+a+"\u30ca","\uff86"+a+"\u30cb",
"\uff87"+a+"\u30cc","\uff88"+a+"\u30cd","\uff89"+a+"\u30ce","\uff8a"+a+"\u30cf","\uff8b"+a+"\u30d2","\uff8c"+a+"\u30d5","\uff8d"+a+"\u30d8","\uff8e"+a+"\u30db","\uff8f"+a+"\u30de","\uff90"+a+"\u30df","\uff91"+a+"\u30e0","\uff92"+a+"\u30e1","\uff93"+a+"\u30e2","\uff94"+a+"\u30e4","\uff95"+a+"\u30e6","\uff96"+a+"\u30e8","\uff97"+a+"\u30e9","\uff98"+a+"\u30ea","\uff99"+a+"\u30eb","\uff9a"+a+"\u30ec","\uff9b"+a+"\u30ed","\uff9c"+a+"\u30ef","\uff66"+a+"\u30f2","\uff9d"+a+"\u30f3","\uff67"+a+"\u30a1","\uff68"+
a+"\u30a3","\uff69"+a+"\u30a5","\uff6a"+a+"\u30a7","\uff6b"+a+"\u30a9","\uff6f"+a+"\u30c3","\uff6c"+a+"\u30e3","\uff6d"+a+"\u30e5","\uff6e"+a+"\u30e7","\uff73\uff9e"+a+"\u30f4","\uff76\uff9e"+a+"\u30ac","\uff77\uff9e"+a+"\u30ae","\uff78\uff9e"+a+"\u30b0","\uff79\uff9e"+a+"\u30b2","\uff7a\uff9e"+a+"\u30b4","\uff7b\uff9e"+a+"\u30b6","\uff7c\uff9e"+a+"\u30b8","\uff7d\uff9e"+a+"\u30ba","\uff7e\uff9e"+a+"\u30bc","\uff7f\uff9e"+a+"\u30be","\uff80\uff9e"+a+"\u30c0","\uff81\uff9e"+a+"\u30c2","\uff82\uff9e"+
a+"\u30c5","\uff83\uff9e"+a+"\u30c7","\uff84\uff9e"+a+"\u30c9","\uff8a\uff9e"+a+"\u30d0","\uff8b\uff9e"+a+"\u30d3","\uff8c\uff9e"+a+"\u30d6","\uff8d\uff9e"+a+"\u30d9","\uff8e\uff9e"+a+"\u30dc","\uff8a\uff9f"+a+"\u30d1","\uff8b\uff9f"+a+"\u30d4","\uff8c\uff9f"+a+"\u30d7","\uff8d\uff9f"+a+"\u30da","\uff8e\uff9f"+a+"\u30dd","!"+a+"\uff01",'"'+a+"\u201d","#"+a+"\uff03","\\$"+a+"\uff04","%"+a+"\uff05","&"+a+"\uff06","'"+a+"\u2019","\\("+a+"\uff08","\\)"+a+"\uff09","\\*"+a+"\uff0a","\\+"+a+"\uff0b","\\,"+
a+"\uff0c","\\-"+a+"\uff0d","\\."+a+"\uff0e","/"+a+"\uff0f","\\:"+a+"\uff1a",";"+a+"\uff1b","<"+a+"\uff1c","="+a+"\uff1d",">"+a+"\uff1e","\\?"+a+"\uff1f","@"+a+"\uff20","\\["+a+"\uff3b","\\\\"+a+"\uffe5","\\]"+a+"\uff3d","\\^"+a+"\uff3e","_"+a+"\uff3f","`"+a+"\u2018","\\{"+a+"\uff5b","\\|"+a+"\uff5c","\\}"+a+"\uff5d","~"+a+"\uff5e","\uff61"+a+"\u3002","\uff62"+a+"\u300c","\uff63"+a+"\u300d","\uff64"+a+"\u3001","\uff65"+a+"\u30fb"]}function fncGetRegExpSeparator(){return"###Separator###"}
function fncGetSearchFoundMessage(a){return fncGetResourceByResourceId("search_found_message_1_prefix")+fncGetResourceByResourceId("search_word_open")+a+fncGetResourceByResourceId("search_word_close")+fncGetResourceByResourceId("search_found_message_1_suffix")}
function fncGetSearchCountMessage(a,b,d){return fncGetResourceByResourceId("search_found_count_message_open")+fncGetResourceByResourceId("search_found_count_message_prefix")+((a-1)*parseInt(fncGetConstantByName("search_show_result_count"))+1)+fncGetResourceByResourceId("search_found_sub_message_to")+b+fncGetResourceByResourceId("search_found_sub_message_1")+d+fncGetResourceByResourceId("search_found_count_message_suffix")+fncGetResourceByResourceId("search_found_count_message_close")}
function fncGetSearchCountMessageBottom(a,b,d){return fncGetResourceByResourceId("search_found_count_message_prefix")+((a-1)*parseInt(fncGetConstantByName("search_show_result_count"))+1)+fncGetResourceByResourceId("search_found_sub_message_to")+b+fncGetResourceByResourceId("search_found_sub_message_1")+d+fncGetResourceByResourceId("search_found_count_message_suffix")}function fncGetEncodeText(a){if(a!=null){a=a.replace(/&/g,"&amp;");a=a.replace(/</g,"&lt;");a=a.replace(/>/g,"&gt;")}return a}
String.prototype.trim=function(){return this.replace(/(^\s+|\s+$)/g,"")};
